### ISSUE TITLE
How to get image and video

### ISSUE THREAD

**Issue by ZheFeng** [json-porn-api/demo#1]
Hi Stephan,

json porn api is really a good project. But I got some question when I use the api.

I'm trying to build a porn video website. When I call the api, I got response like this:

```
{
    ...
    imageKeyIds: [
        5187484686221312,
        5666736732897280
    ],
    images: [
    {
        key: {
            kind: "ImageEntry",
            id: 5187484686221312
        },
        url: "http://img7.pixhost.org/images/135/32378086_1.jpg",
        type: 1,
        entryType: 3
    },
    ...
    ],
    ...
    downloads: [
    {
        key: {
            parentKey: {
                kind: "PornEntry",
                id: 5162729165815808
            },
        kind: "DownloadEntry",
        id: 5161210659995648
        },
        url: "http://k2s.cc/file/ce478ef561976/Filthiest.Cums.First.XXX.DVDRip.x264-Fapulous.mp4",
        fileSize: 0,
        hosterKeyId: 5982664494415872,
        downloadType: 4,
        entryType: 4
    },    ...
    ],
    ...
}
```

When I try to show the image, I'm using images[0].url
When I try to play the video, I'm using downloads[0].url

But seems both url is not working. So I want to ask how to get the correct image there to show in my website? 

Thanks

**Comment by Steppschuh** [comment]
Hey,
to show images, you need to use the [image endpoint](https://market.mashape.com/steppschuh/json-porn/#images) and provide an imageKeyId. There are convenience functions in [pornapi.js](https://github.com/json-porn-api/demo/blob/gh-pages/js/pornapi.js#L409):

``` javascript
api.getImageUrlById = function(imageKeyId) {
    return api.getResizedImageUrlById(imageKeyId, "original");
}

api.getResizedImageUrlById = function(imageKeyId, size) {
    return ENDPOINT_IMAGE + imageKeyId + "/" + size + ".jpg";
}
```

The links are download links from different hosters, nothing you could stream. If you want to show videos on your site, query for streams instead of downloads and embed the player from the source (e.g. porn.com). With the next update, porn entries with streams will contain the embed url of the player right in the JSON.
